docker and non-docker support

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -8,8 +8,8 @@ on:
     branches: [master]
 
 jobs:
-  integration-test:
-    name: Run integration tests against MCP
+  integration-test-no-docker:
+    name: Run integration tests against MCP as a binary, invoking docker images for each language
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v6
@@ -31,6 +31,64 @@ jobs:
         run: |
           cargo build
           cargo run & # nohup
+
+      - name: Wait for port 8000
+        run: |
+          # Loop until localhost:8000 returns a 200 OK
+          timeout 60s bash -c 'until curl -s localhost:8000; do sleep 1; done'
+
+      - name: Test tool list
+        run: |
+          tool_list=$(npx @modelcontextprotocol/inspector http://localhost:8000/mcp --cli --method tools/list)
+          result=$(echo $tool_list | jq -r '.tools  | length')
+          if [ $result != "4" ]; then
+            echo "Assertion failed: $result"
+            exit 1
+          fi
+
+      - name: Test python tool call
+        run: |
+          tool_call=$(npx @modelcontextprotocol/inspector --cli http://localhost:8000/mcp --method tools/call --tool-name run_python --tool-arg entry_file=integration-tests/helloworld.py --tool-arg project_dir=$(pwd))
+          result=$(echo $tool_call | jq -r '.isError ')
+          if [ $result != "false" ]; then
+            echo "Assertion failed: $result"
+            echo "Tool call: $tool_call"
+            exit 1
+          fi
+
+      - name: Test javascript tool call
+        run: |
+          tool_call=$(npx @modelcontextprotocol/inspector --cli http://localhost:8000/mcp --method tools/call --tool-name run_javascript --tool-arg entry_file=integration-tests/helloworld.js --tool-arg project_dir=$(pwd))
+          result=$(echo $tool_call | jq -r '.isError ')
+          if [ $result != "false" ]; then
+            echo "Assertion failed: $result"
+            echo "Tool call: $tool_call"
+            exit 1
+          fi
+
+      - name: Test rust tool call
+        run: |
+          tool_call=$(npx @modelcontextprotocol/inspector --cli http://localhost:8000/mcp --method tools/call --tool-name run_rust --tool-arg execution_type=test --tool-arg project_dir=$(pwd))
+          result=$(echo $tool_call | jq -r '.isError ')
+          if [ $result != "false" ]; then
+            echo "Assertion failed: $result"
+            echo "Tool call: $tool_call"
+            exit 1
+          fi
+  integration-test-with-docker:
+    name: Run integration tests against MCP hosted in self-contained docker with languages included in docker
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v6
+        with:
+          fetch-depth: 0
+      - name: build python image
+        run: |
+          docker build -t main-docker -f docker/Dockerfile ./
+
+      - name: Start mcp
+        run: |
+          docker run -d main-docker -p 8000:8000 -v $(pwd)/integration-tests:/home/appuser/code_location
 
       - name: Wait for port 8000
         run: |
