added javascript

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -31,7 +31,7 @@ jobs:
         run: |
           tool_list=$(npx @modelcontextprotocol/inspector http://localhost:8000/mcp --cli --method tools/list)
           result=$(echo $tool_list | jq -r '.tools  | length')
-          if [ $result != "3" ]; then
+          if [ $result != "4" ]; then
             echo "Assertion failed: $result"
             exit 1
           fi
@@ -39,6 +39,15 @@ jobs:
       - name: Test python tool call
         run: |
           tool_call=$(npx @modelcontextprotocol/inspector --cli http://localhost:8000/mcp --method tools/call --tool-name run_python --tool-arg entry_file=integration-tests/helloworld.py --tool-arg project_dir=$(pwd))
+          result=$(echo $tool_call | jq -r '.isError ')
+          if [ $result != "false" ]; then
+            echo "Assertion failed: $result"
+            exit 1
+          fi
+
+      - name: Test javascript tool call
+        run: |
+          tool_call=$(npx @modelcontextprotocol/inspector --cli http://localhost:8000/mcp --method tools/call --tool-name run_javascript --tool-arg entry_file=integration-tests/helloworld.js --tool-arg project_dir=$(pwd))
           result=$(echo $tool_call | jq -r '.isError ')
           if [ $result != "false" ]; then
             echo "Assertion failed: $result"
